### PR TITLE
Fix #10: Correctly count SASS/SCSS files in all dirs

### LINKED ISSUE #10: Fix file count output when executing compile goal
File count is incorrectly calculated when the input folder contains subfolders with compilable sass/scss files.

### PR DESCRIPTION
**Pull request by melloware**
Walks the directories counting only SASS/SCSS files

### CODE REVIEW

**Comment by cleydyr** [comment]
Hey, @melloware .

Thanks again for this contribution. I've rebased it and pushed the branch issue-15 to the repo. There are some edge cases that I could cover in the [issue-15](https://github.com/melloware/dart-sass-maven-plugin/compare/DS10...cleydyr:issue-15) branch (see fix commits) but others are still there related mainly to the lowercasing of the path, which may include false positives in the count in case-sensitive filesystems.

I'll check those later.

**Comment by cleydyr** [comment]
Hey, @melloware . I've gone ahead and tested the Dart Sass distribution available [here](https://github.com/sass/dart-sass/releases/download/1.50.0/dart-sass-1.50.0-windows-x64.zip) and I see that the sass script doesn't compile one file ending in .SCSS unless I use [one-to-one mode](https://sass-lang.com/documentation/cli/dart-sass#one-to-one-mode), which is not the mode used by this plugin. Can you please clarify which case would be covered by lowercasing the file names?

**Comment by melloware** [comment]
Nice work!  My thought was that `.SASS` and `.sass` and `.Sass` are all identical.   So if you only check for `.sass` you will be incorrectly counting files without lowercasing first.

**Comment by melloware** [comment]
Or ".CSS" ".cSs" etc.   Feels more bulletproof to lowercase before counting.

**Comment by cleydyr** [comment]
Did you check if the count logged by the plugin matches the actual processed file count in those cases (files ending with . SASS, Sass, etc) after the changes introduced by DS10 branch in your fork?

**Comment by melloware** [comment]
Let me give it a shot with your branch changes and I will let you know. I run on Windows and Linux but not MacOS so not sure if each OS will be different.

**Comment by cleydyr** [comment]
Oh! I must clarify that in [this previous comment](https://github.com/cleydyr/dart-sass-maven-plugin/pull/15#issuecomment-1100956780) I used a Windows 11 VM running in Parallels Desktop to try to reproduce case-insensitive. :)

Also, [the Dart Sass source code](https://github.com/sass/dart-sass/blob/main/lib/src/executable/options.dart#L391-L407) doesn't indicate that it will process allowed files regardless of the file extension case.

**Comment by melloware** [comment]
Ahh ok then feel free to pull the lowercase step if you have verified already!

**Comment by melloware** [comment]
@cleydyr Great work on this plugin. I have been using the other Ruby Sass plugin for years and I was about to sit down and write this exact plugin so I am glad I found yours!

**Comment by cleydyr** [comment]
Fixed in master. See https://github.com/cleydyr/dart-sass-maven-plugin/compare/49bf024...54c1a91

**Comment by melloware** [comment]
you rock!

**Pull request closed without merging**
